export const labels = {
  material: {
    primary: ["--c-primary", "--c-primary-l", "--c-primary-d"],
    secondary: ["--c-secondary", "--c-secondary-l", "--c-secondary-d"],
    neutral: [
      "--c-neutral-1",
      "--c-neutral-2",
      "--c-neutral-3",
      "--c-neutral-4",
      "--c-neutral-5",
      "--c-neutral-6",
    ],
  },
  tailwind: {
    primary: [
      "--c-primary-50",
      "--c-primary-100",
      "--c-primary-200",
      "--c-primary-300",
      "--c-primary-400",
      "--c-primary-500",
      "--c-primary-600",
      "--c-primary-700",
      "--c-primary-800",
      "--c-primary-900",
    ],
    secondary: [
      "--c-secondary-50",
      "--c-secondary-100",
      "--c-secondary-200",
      "--c-secondary-300",
      "--c-secondary-400",
      "--c-secondary-500",
      "--c-secondary-600",
      "--c-secondary-700",
      "--c-secondary-800",
      "--c-secondary-900",
    ],
    neutral: [
      "--c-neutral-50",
      "--c-neutral-100",
      "--c-neutral-200",
      "--c-neutral-300",
      "--c-neutral-400",
      "--c-neutral-500",
      "--c-neutral-600",
      "--c-neutral-700",
      "--c-neutral-800",
      "--c-neutral-900",
    ],
  },
};
